# Generated by Django 5.1.3 on 2024-12-11 18:38

import builtins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='project',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='timetrackapp.project'),
            preserve_default=False,
        ),
    ]
