# Generated by Django 5.1.3 on 2024-12-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrackapp', '0002_alter_goal_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetrackapp.project'),
        ),
    ]
